spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://112.126.90.93:3306/hl?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Longlian111!!!
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8888
#redis cluster 123.57.224.112:7000-7005
spring.redis:
  clusterNodes: 123.57.224.112:7000,123.57.224.112:7001,123.57.224.112:7002,123.57.224.112:7003,123.57.224.112:7004,123.57.224.112:7005
  commandTimeout: 3000
  #soTimeout 返回值的超时时间
  soTimeout: 3000
  # maxAttempts：出现异常最大重试次数
  maxAttempts: 5
  # password 密码
  #password: a2VsZW50MTIzNDU2


#pagehelper 分页
pagehelper:
  #dialect: com.github.pagehelper.dialect.helper.MySqlDialect
  reasonable: false
  autoDialect: true

mybatis:
  type-aliases-package: com.smart.homelink.model

