package com.smart.homelink.dao;

import com.smart.homelink.model.AirSensorRecord;
import org.apache.ibatis.jdbc.SQL;

public class AirSensorRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_sensor_record
     *
     * @mbg.generated
     */
    public String insertSelective(AirSensorRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("air_sensor_record");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getcId() != null) {
            sql.VALUES("c_id", "#{cId,jdbcType=BIGINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHomeId() != null) {
            sql.VALUES("home_id", "#{homeId,jdbcType=BIGINT}");
        }
        
        if (record.getTemp() != null) {
            sql.VALUES("temp", "#{temp,jdbcType=DECIMAL}");
        }
        
        if (record.getHumidity() != null) {
            sql.VALUES("humidity", "#{humidity,jdbcType=DECIMAL}");
        }
        
        if (record.getAltitude() != null) {
            sql.VALUES("altitude", "#{altitude,jdbcType=DECIMAL}");
        }
        
        if (record.getQnh() != null) {
            sql.VALUES("qnh", "#{qnh,jdbcType=DECIMAL}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_sensor_record
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(AirSensorRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("air_sensor_record");
        
        if (record.getcId() != null) {
            sql.SET("c_id = #{cId,jdbcType=BIGINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getHomeId() != null) {
            sql.SET("home_id = #{homeId,jdbcType=BIGINT}");
        }
        
        if (record.getTemp() != null) {
            sql.SET("temp = #{temp,jdbcType=DECIMAL}");
        }
        
        if (record.getHumidity() != null) {
            sql.SET("humidity = #{humidity,jdbcType=DECIMAL}");
        }
        
        if (record.getAltitude() != null) {
            sql.SET("altitude = #{altitude,jdbcType=DECIMAL}");
        }
        
        if (record.getQnh() != null) {
            sql.SET("qnh = #{qnh,jdbcType=DECIMAL}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}