package com.smart.homelink.dao;

import com.smart.homelink.model.AppMsg;
import org.apache.ibatis.jdbc.SQL;

public class AppMsgSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_msg
     *
     * @mbg.generated
     */
    public String insertSelective(AppMsg record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("app_msg");
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getAppId() != null) {
            sql.VALUES("APP_ID", "#{appId,jdbcType=BIGINT}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("TYPE", "#{type,jdbcType=INTEGER}");
        }
        
        if (record.getTableId() != null) {
            sql.VALUES("TABLE_ID", "#{tableId,jdbcType=BIGINT}");
        }
        
        if (record.getContent() != null) {
            sql.VALUES("CONTENT", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("STATUS", "#{status,jdbcType=BIGINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReadTime() != null) {
            sql.VALUES("READ_TIME", "#{readTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getcAct() != null) {
            sql.VALUES("C_ACT", "#{cAct,jdbcType=VARCHAR}");
        }
        
        if (record.getCourseStatus() != null) {
            sql.VALUES("COURSE_STATUS", "#{courseStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getTeacherId() != null) {
            sql.VALUES("TEACHER_ID", "#{teacherId,jdbcType=BIGINT}");
        }
        
        if (record.getIsSeriesCourse() != null) {
            sql.VALUES("IS_SERIES_COURSE", "#{isSeriesCourse,jdbcType=VARCHAR}");
        }
        
        if (record.getSeriesCourseId() != null) {
            sql.VALUES("SERIES_COURSE_ID", "#{seriesCourseId,jdbcType=BIGINT}");
        }
        
        if (record.getRoomId() != null) {
            sql.VALUES("ROOM_ID", "#{roomId,jdbcType=BIGINT}");
        }
        
        if (record.getIsUpdate() != null) {
            sql.VALUES("IS_UPDATE", "#{isUpdate,jdbcType=VARCHAR}");
        }
        
        if (record.getPushUrl() != null) {
            sql.VALUES("PUSH_URL", "#{pushUrl,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_msg
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(AppMsg record) {
        SQL sql = new SQL();
        sql.UPDATE("app_msg");
        
        if (record.getAppId() != null) {
            sql.SET("APP_ID = #{appId,jdbcType=BIGINT}");
        }
        
        if (record.getType() != null) {
            sql.SET("TYPE = #{type,jdbcType=INTEGER}");
        }
        
        if (record.getTableId() != null) {
            sql.SET("TABLE_ID = #{tableId,jdbcType=BIGINT}");
        }
        
        if (record.getContent() != null) {
            sql.SET("CONTENT = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("STATUS = #{status,jdbcType=BIGINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReadTime() != null) {
            sql.SET("READ_TIME = #{readTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getcAct() != null) {
            sql.SET("C_ACT = #{cAct,jdbcType=VARCHAR}");
        }
        
        if (record.getCourseStatus() != null) {
            sql.SET("COURSE_STATUS = #{courseStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getTeacherId() != null) {
            sql.SET("TEACHER_ID = #{teacherId,jdbcType=BIGINT}");
        }
        
        if (record.getIsSeriesCourse() != null) {
            sql.SET("IS_SERIES_COURSE = #{isSeriesCourse,jdbcType=VARCHAR}");
        }
        
        if (record.getSeriesCourseId() != null) {
            sql.SET("SERIES_COURSE_ID = #{seriesCourseId,jdbcType=BIGINT}");
        }
        
        if (record.getRoomId() != null) {
            sql.SET("ROOM_ID = #{roomId,jdbcType=BIGINT}");
        }
        
        if (record.getIsUpdate() != null) {
            sql.SET("IS_UPDATE = #{isUpdate,jdbcType=VARCHAR}");
        }
        
        if (record.getPushUrl() != null) {
            sql.SET("PUSH_URL = #{pushUrl,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("ID = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}