package com.smart.homelink.dao;

import com.smart.homelink.model.ChatRoomMsg;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ChatRoomMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    @Delete({
        "delete from chat_room_msg",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    @Insert({
        "insert into chat_room_msg (ID, FROM_ACCOUNT, ",
        "FROM_CLIENT_TYPE, MSGID_CLIENT, ",
        "FROM_EXT, FROM_AVATOR, ",
        "FROM_NICK, MSG_TIMESTAMP, ",
        "RESEND_FLAG, MSG_TYPE, ",
        "CHAT_ROOM_ID, QUIZ_OR_REPLY, ",
        "REPLY_ID, REPLY_NAME, ",
        "REPLY_AVATOR, CUSTOM_MSG_TYPE, ",
        "IS_GARBAGE, COURSE_ID, ",
        "LIVE_TOPIC, START_PLAY_TIME, ",
        "STOP_PLAY_TIME, ATTACH, ",
        "MSG_BODY)",
        "values (#{id,jdbcType=BIGINT}, #{fromAccount,jdbcType=BIGINT}, ",
        "#{fromClientType,jdbcType=VARCHAR}, #{msgidClient,jdbcType=VARCHAR}, ",
        "#{fromExt,jdbcType=VARCHAR}, #{fromAvator,jdbcType=VARCHAR}, ",
        "#{fromNick,jdbcType=VARCHAR}, #{msgTimestamp,jdbcType=TIMESTAMP}, ",
        "#{resendFlag,jdbcType=VARCHAR}, #{msgType,jdbcType=VARCHAR}, ",
        "#{chatRoomId,jdbcType=BIGINT}, #{quizOrReply,jdbcType=VARCHAR}, ",
        "#{replyId,jdbcType=BIGINT}, #{replyName,jdbcType=VARCHAR}, ",
        "#{replyAvator,jdbcType=VARCHAR}, #{customMsgType,jdbcType=VARCHAR}, ",
        "#{isGarbage,jdbcType=VARCHAR}, #{courseId,jdbcType=BIGINT}, ",
        "#{liveTopic,jdbcType=VARCHAR}, #{startPlayTime,jdbcType=BIGINT}, ",
        "#{stopPlayTime,jdbcType=BIGINT}, #{attach,jdbcType=LONGVARCHAR}, ",
        "#{msgBody,jdbcType=LONGVARCHAR})"
    })
    int insert(ChatRoomMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    @InsertProvider(type=ChatRoomMsgSqlProvider.class, method="insertSelective")
    int insertSelective(ChatRoomMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, FROM_ACCOUNT, FROM_CLIENT_TYPE, MSGID_CLIENT, FROM_EXT, FROM_AVATOR, FROM_NICK, ",
        "MSG_TIMESTAMP, RESEND_FLAG, MSG_TYPE, CHAT_ROOM_ID, QUIZ_OR_REPLY, REPLY_ID, ",
        "REPLY_NAME, REPLY_AVATOR, CUSTOM_MSG_TYPE, IS_GARBAGE, COURSE_ID, LIVE_TOPIC, ",
        "START_PLAY_TIME, STOP_PLAY_TIME, ATTACH, MSG_BODY",
        "from chat_room_msg",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="FROM_ACCOUNT", property="fromAccount", jdbcType=JdbcType.BIGINT),
        @Result(column="FROM_CLIENT_TYPE", property="fromClientType", jdbcType=JdbcType.VARCHAR),
        @Result(column="MSGID_CLIENT", property="msgidClient", jdbcType=JdbcType.VARCHAR),
        @Result(column="FROM_EXT", property="fromExt", jdbcType=JdbcType.VARCHAR),
        @Result(column="FROM_AVATOR", property="fromAvator", jdbcType=JdbcType.VARCHAR),
        @Result(column="FROM_NICK", property="fromNick", jdbcType=JdbcType.VARCHAR),
        @Result(column="MSG_TIMESTAMP", property="msgTimestamp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESEND_FLAG", property="resendFlag", jdbcType=JdbcType.VARCHAR),
        @Result(column="MSG_TYPE", property="msgType", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHAT_ROOM_ID", property="chatRoomId", jdbcType=JdbcType.BIGINT),
        @Result(column="QUIZ_OR_REPLY", property="quizOrReply", jdbcType=JdbcType.VARCHAR),
        @Result(column="REPLY_ID", property="replyId", jdbcType=JdbcType.BIGINT),
        @Result(column="REPLY_NAME", property="replyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="REPLY_AVATOR", property="replyAvator", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUSTOM_MSG_TYPE", property="customMsgType", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_GARBAGE", property="isGarbage", jdbcType=JdbcType.VARCHAR),
        @Result(column="COURSE_ID", property="courseId", jdbcType=JdbcType.BIGINT),
        @Result(column="LIVE_TOPIC", property="liveTopic", jdbcType=JdbcType.VARCHAR),
        @Result(column="START_PLAY_TIME", property="startPlayTime", jdbcType=JdbcType.BIGINT),
        @Result(column="STOP_PLAY_TIME", property="stopPlayTime", jdbcType=JdbcType.BIGINT),
        @Result(column="ATTACH", property="attach", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="MSG_BODY", property="msgBody", jdbcType=JdbcType.LONGVARCHAR)
    })
    ChatRoomMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ChatRoomMsgSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ChatRoomMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    @Update({
        "update chat_room_msg",
        "set FROM_ACCOUNT = #{fromAccount,jdbcType=BIGINT},",
          "FROM_CLIENT_TYPE = #{fromClientType,jdbcType=VARCHAR},",
          "MSGID_CLIENT = #{msgidClient,jdbcType=VARCHAR},",
          "FROM_EXT = #{fromExt,jdbcType=VARCHAR},",
          "FROM_AVATOR = #{fromAvator,jdbcType=VARCHAR},",
          "FROM_NICK = #{fromNick,jdbcType=VARCHAR},",
          "MSG_TIMESTAMP = #{msgTimestamp,jdbcType=TIMESTAMP},",
          "RESEND_FLAG = #{resendFlag,jdbcType=VARCHAR},",
          "MSG_TYPE = #{msgType,jdbcType=VARCHAR},",
          "CHAT_ROOM_ID = #{chatRoomId,jdbcType=BIGINT},",
          "QUIZ_OR_REPLY = #{quizOrReply,jdbcType=VARCHAR},",
          "REPLY_ID = #{replyId,jdbcType=BIGINT},",
          "REPLY_NAME = #{replyName,jdbcType=VARCHAR},",
          "REPLY_AVATOR = #{replyAvator,jdbcType=VARCHAR},",
          "CUSTOM_MSG_TYPE = #{customMsgType,jdbcType=VARCHAR},",
          "IS_GARBAGE = #{isGarbage,jdbcType=VARCHAR},",
          "COURSE_ID = #{courseId,jdbcType=BIGINT},",
          "LIVE_TOPIC = #{liveTopic,jdbcType=VARCHAR},",
          "START_PLAY_TIME = #{startPlayTime,jdbcType=BIGINT},",
          "STOP_PLAY_TIME = #{stopPlayTime,jdbcType=BIGINT},",
          "ATTACH = #{attach,jdbcType=LONGVARCHAR},",
          "MSG_BODY = #{msgBody,jdbcType=LONGVARCHAR}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(ChatRoomMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    @Update({
        "update chat_room_msg",
        "set FROM_ACCOUNT = #{fromAccount,jdbcType=BIGINT},",
          "FROM_CLIENT_TYPE = #{fromClientType,jdbcType=VARCHAR},",
          "MSGID_CLIENT = #{msgidClient,jdbcType=VARCHAR},",
          "FROM_EXT = #{fromExt,jdbcType=VARCHAR},",
          "FROM_AVATOR = #{fromAvator,jdbcType=VARCHAR},",
          "FROM_NICK = #{fromNick,jdbcType=VARCHAR},",
          "MSG_TIMESTAMP = #{msgTimestamp,jdbcType=TIMESTAMP},",
          "RESEND_FLAG = #{resendFlag,jdbcType=VARCHAR},",
          "MSG_TYPE = #{msgType,jdbcType=VARCHAR},",
          "CHAT_ROOM_ID = #{chatRoomId,jdbcType=BIGINT},",
          "QUIZ_OR_REPLY = #{quizOrReply,jdbcType=VARCHAR},",
          "REPLY_ID = #{replyId,jdbcType=BIGINT},",
          "REPLY_NAME = #{replyName,jdbcType=VARCHAR},",
          "REPLY_AVATOR = #{replyAvator,jdbcType=VARCHAR},",
          "CUSTOM_MSG_TYPE = #{customMsgType,jdbcType=VARCHAR},",
          "IS_GARBAGE = #{isGarbage,jdbcType=VARCHAR},",
          "COURSE_ID = #{courseId,jdbcType=BIGINT},",
          "LIVE_TOPIC = #{liveTopic,jdbcType=VARCHAR},",
          "START_PLAY_TIME = #{startPlayTime,jdbcType=BIGINT},",
          "STOP_PLAY_TIME = #{stopPlayTime,jdbcType=BIGINT}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ChatRoomMsg record);
}