package com.smart.homelink.dao;

import com.smart.homelink.model.ChatRoomMsg;
import org.apache.ibatis.jdbc.SQL;

public class ChatRoomMsgSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    public String insertSelective(ChatRoomMsg record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("chat_room_msg");
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getFromAccount() != null) {
            sql.VALUES("FROM_ACCOUNT", "#{fromAccount,jdbcType=BIGINT}");
        }
        
        if (record.getFromClientType() != null) {
            sql.VALUES("FROM_CLIENT_TYPE", "#{fromClientType,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgidClient() != null) {
            sql.VALUES("MSGID_CLIENT", "#{msgidClient,jdbcType=VARCHAR}");
        }
        
        if (record.getFromExt() != null) {
            sql.VALUES("FROM_EXT", "#{fromExt,jdbcType=VARCHAR}");
        }
        
        if (record.getFromAvator() != null) {
            sql.VALUES("FROM_AVATOR", "#{fromAvator,jdbcType=VARCHAR}");
        }
        
        if (record.getFromNick() != null) {
            sql.VALUES("FROM_NICK", "#{fromNick,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgTimestamp() != null) {
            sql.VALUES("MSG_TIMESTAMP", "#{msgTimestamp,jdbcType=TIMESTAMP}");
        }
        
        if (record.getResendFlag() != null) {
            sql.VALUES("RESEND_FLAG", "#{resendFlag,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgType() != null) {
            sql.VALUES("MSG_TYPE", "#{msgType,jdbcType=VARCHAR}");
        }
        
        if (record.getChatRoomId() != null) {
            sql.VALUES("CHAT_ROOM_ID", "#{chatRoomId,jdbcType=BIGINT}");
        }
        
        if (record.getQuizOrReply() != null) {
            sql.VALUES("QUIZ_OR_REPLY", "#{quizOrReply,jdbcType=VARCHAR}");
        }
        
        if (record.getReplyId() != null) {
            sql.VALUES("REPLY_ID", "#{replyId,jdbcType=BIGINT}");
        }
        
        if (record.getReplyName() != null) {
            sql.VALUES("REPLY_NAME", "#{replyName,jdbcType=VARCHAR}");
        }
        
        if (record.getReplyAvator() != null) {
            sql.VALUES("REPLY_AVATOR", "#{replyAvator,jdbcType=VARCHAR}");
        }
        
        if (record.getCustomMsgType() != null) {
            sql.VALUES("CUSTOM_MSG_TYPE", "#{customMsgType,jdbcType=VARCHAR}");
        }
        
        if (record.getIsGarbage() != null) {
            sql.VALUES("IS_GARBAGE", "#{isGarbage,jdbcType=VARCHAR}");
        }
        
        if (record.getCourseId() != null) {
            sql.VALUES("COURSE_ID", "#{courseId,jdbcType=BIGINT}");
        }
        
        if (record.getLiveTopic() != null) {
            sql.VALUES("LIVE_TOPIC", "#{liveTopic,jdbcType=VARCHAR}");
        }
        
        if (record.getStartPlayTime() != null) {
            sql.VALUES("START_PLAY_TIME", "#{startPlayTime,jdbcType=BIGINT}");
        }
        
        if (record.getStopPlayTime() != null) {
            sql.VALUES("STOP_PLAY_TIME", "#{stopPlayTime,jdbcType=BIGINT}");
        }
        
        if (record.getAttach() != null) {
            sql.VALUES("ATTACH", "#{attach,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getMsgBody() != null) {
            sql.VALUES("MSG_BODY", "#{msgBody,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_room_msg
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(ChatRoomMsg record) {
        SQL sql = new SQL();
        sql.UPDATE("chat_room_msg");
        
        if (record.getFromAccount() != null) {
            sql.SET("FROM_ACCOUNT = #{fromAccount,jdbcType=BIGINT}");
        }
        
        if (record.getFromClientType() != null) {
            sql.SET("FROM_CLIENT_TYPE = #{fromClientType,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgidClient() != null) {
            sql.SET("MSGID_CLIENT = #{msgidClient,jdbcType=VARCHAR}");
        }
        
        if (record.getFromExt() != null) {
            sql.SET("FROM_EXT = #{fromExt,jdbcType=VARCHAR}");
        }
        
        if (record.getFromAvator() != null) {
            sql.SET("FROM_AVATOR = #{fromAvator,jdbcType=VARCHAR}");
        }
        
        if (record.getFromNick() != null) {
            sql.SET("FROM_NICK = #{fromNick,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgTimestamp() != null) {
            sql.SET("MSG_TIMESTAMP = #{msgTimestamp,jdbcType=TIMESTAMP}");
        }
        
        if (record.getResendFlag() != null) {
            sql.SET("RESEND_FLAG = #{resendFlag,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgType() != null) {
            sql.SET("MSG_TYPE = #{msgType,jdbcType=VARCHAR}");
        }
        
        if (record.getChatRoomId() != null) {
            sql.SET("CHAT_ROOM_ID = #{chatRoomId,jdbcType=BIGINT}");
        }
        
        if (record.getQuizOrReply() != null) {
            sql.SET("QUIZ_OR_REPLY = #{quizOrReply,jdbcType=VARCHAR}");
        }
        
        if (record.getReplyId() != null) {
            sql.SET("REPLY_ID = #{replyId,jdbcType=BIGINT}");
        }
        
        if (record.getReplyName() != null) {
            sql.SET("REPLY_NAME = #{replyName,jdbcType=VARCHAR}");
        }
        
        if (record.getReplyAvator() != null) {
            sql.SET("REPLY_AVATOR = #{replyAvator,jdbcType=VARCHAR}");
        }
        
        if (record.getCustomMsgType() != null) {
            sql.SET("CUSTOM_MSG_TYPE = #{customMsgType,jdbcType=VARCHAR}");
        }
        
        if (record.getIsGarbage() != null) {
            sql.SET("IS_GARBAGE = #{isGarbage,jdbcType=VARCHAR}");
        }
        
        if (record.getCourseId() != null) {
            sql.SET("COURSE_ID = #{courseId,jdbcType=BIGINT}");
        }
        
        if (record.getLiveTopic() != null) {
            sql.SET("LIVE_TOPIC = #{liveTopic,jdbcType=VARCHAR}");
        }
        
        if (record.getStartPlayTime() != null) {
            sql.SET("START_PLAY_TIME = #{startPlayTime,jdbcType=BIGINT}");
        }
        
        if (record.getStopPlayTime() != null) {
            sql.SET("STOP_PLAY_TIME = #{stopPlayTime,jdbcType=BIGINT}");
        }
        
        if (record.getAttach() != null) {
            sql.SET("ATTACH = #{attach,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getMsgBody() != null) {
            sql.SET("MSG_BODY = #{msgBody,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("ID = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}