package com.smart.homelink.dao;

import com.smart.homelink.model.HomeUser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface HomeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from home_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into home_user (id, home_id, ",
        "user_id)",
        "values (#{id,jdbcType=BIGINT}, #{homeId,jdbcType=BIGINT}, ",
        "#{userId,jdbcType=BIGINT})"
    })
    int insert(HomeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=HomeUserSqlProvider.class, method="insertSelective")
    int insertSelective(HomeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, home_id, user_id",
        "from home_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="home_id", property="homeId", jdbcType=JdbcType.BIGINT),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT)
    })
    HomeUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=HomeUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(HomeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_user
     *
     * @mbg.generated
     */
    @Update({
        "update home_user",
        "set home_id = #{homeId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(HomeUser record);
}