package com.smart.homelink.dao;

import com.smart.homelink.model.HomeUser;
import org.apache.ibatis.jdbc.SQL;

public class HomeUserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_user
     *
     * @mbg.generated
     */
    public String insertSelective(HomeUser record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("home_user");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getHomeId() != null) {
            sql.VALUES("home_id", "#{homeId,jdbcType=BIGINT}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_user
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(HomeUser record) {
        SQL sql = new SQL();
        sql.UPDATE("home_user");
        
        if (record.getHomeId() != null) {
            sql.SET("home_id = #{homeId,jdbcType=BIGINT}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}