package com.smart.homelink.dao;

import com.smart.homelink.model.Home;
import org.apache.ibatis.jdbc.SQL;

public class HomeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home
     *
     * @mbg.generated
     */
    public String insertSelective(Home record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("home");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getHomeName() != null) {
            sql.VALUES("home_name", "#{homeName,jdbcType=VARCHAR}");
        }
        
        if (record.getBelongUserId() != null) {
            sql.VALUES("belong_user_id", "#{belongUserId,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Home record) {
        SQL sql = new SQL();
        sql.UPDATE("home");
        
        if (record.getHomeName() != null) {
            sql.SET("home_name = #{homeName,jdbcType=VARCHAR}");
        }
        
        if (record.getBelongUserId() != null) {
            sql.SET("belong_user_id = #{belongUserId,jdbcType=BIGINT}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}