package com.smart.homelink.dao;

import com.smart.homelink.model.MRes;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res
     *
     * @mbg.generated
     */
    @Delete({
        "delete from m_res",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res
     *
     * @mbg.generated
     */
    @Insert({
        "insert into m_res (id, name, ",
        "parent_id, type, sort, ",
        "status, url, res_pic, ",
        "description)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=BIGINT}, #{type,jdbcType=VARCHAR}, #{sort,jdbcType=INTEGER}, ",
        "#{status,jdbcType=INTEGER}, #{url,jdbcType=VARCHAR}, #{resPic,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR})"
    })
    int insert(MRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res
     *
     * @mbg.generated
     */
    @InsertProvider(type=MResSqlProvider.class, method="insertSelective")
    int insertSelective(MRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, parent_id, type, sort, status, url, res_pic, description",
        "from m_res",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.BIGINT),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="res_pic", property="resPic", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    MRes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MResSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res
     *
     * @mbg.generated
     */
    @Update({
        "update m_res",
        "set name = #{name,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=BIGINT},",
          "type = #{type,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "url = #{url,jdbcType=VARCHAR},",
          "res_pic = #{resPic,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MRes record);
}