package com.smart.homelink.dao;

import com.smart.homelink.model.MResRel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MResRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res_rel
     *
     * @mbg.generated
     */
    @Delete({
        "delete from m_res_rel",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res_rel
     *
     * @mbg.generated
     */
    @Insert({
        "insert into m_res_rel (id, res_id, ",
        "rel_id)",
        "values (#{id,jdbcType=BIGINT}, #{resId,jdbcType=BIGINT}, ",
        "#{relId,jdbcType=BIGINT})"
    })
    int insert(MResRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res_rel
     *
     * @mbg.generated
     */
    @InsertProvider(type=MResRelSqlProvider.class, method="insertSelective")
    int insertSelective(MResRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res_rel
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, res_id, rel_id",
        "from m_res_rel",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="res_id", property="resId", jdbcType=JdbcType.BIGINT),
        @Result(column="rel_id", property="relId", jdbcType=JdbcType.BIGINT)
    })
    MResRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res_rel
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MResRelSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MResRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res_rel
     *
     * @mbg.generated
     */
    @Update({
        "update m_res_rel",
        "set res_id = #{resId,jdbcType=BIGINT},",
          "rel_id = #{relId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MResRel record);
}