package com.smart.homelink.dao;

import com.smart.homelink.model.MResRel;
import org.apache.ibatis.jdbc.SQL;

public class MResRelSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res_rel
     *
     * @mbg.generated
     */
    public String insertSelective(MResRel record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("m_res_rel");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getResId() != null) {
            sql.VALUES("res_id", "#{resId,jdbcType=BIGINT}");
        }
        
        if (record.getRelId() != null) {
            sql.VALUES("rel_id", "#{relId,jdbcType=BIGINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_res_rel
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MResRel record) {
        SQL sql = new SQL();
        sql.UPDATE("m_res_rel");
        
        if (record.getResId() != null) {
            sql.SET("res_id = #{resId,jdbcType=BIGINT}");
        }
        
        if (record.getRelId() != null) {
            sql.SET("rel_id = #{relId,jdbcType=BIGINT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}