package com.smart.homelink.dao;

import com.smart.homelink.model.SmartComponent;
import org.apache.ibatis.jdbc.SQL;

public class SmartComponentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_component
     *
     * @mbg.generated
     */
    public String insertSelective(SmartComponent record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("smart_component");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getTypeId() != null) {
            sql.VALUES("type_id", "#{typeId,jdbcType=BIGINT}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsControllerCenter() != null) {
            sql.VALUES("is_controller_center", "#{isControllerCenter,jdbcType=INTEGER}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUserId() != null) {
            sql.VALUES("create_user_id", "#{createUserId,jdbcType=BIGINT}");
        }
        
        if (record.getHomeId() != null) {
            sql.VALUES("home_id", "#{homeId,jdbcType=BIGINT}");
        }
        
        if (record.getIcName() != null) {
            sql.VALUES("ic_name", "#{icName,jdbcType=VARCHAR}");
        }
        
        if (record.getFirmwareVersion() != null) {
            sql.VALUES("firmware_version", "#{firmwareVersion,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_component
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(SmartComponent record) {
        SQL sql = new SQL();
        sql.UPDATE("smart_component");
        
        if (record.getTypeId() != null) {
            sql.SET("type_id = #{typeId,jdbcType=BIGINT}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsControllerCenter() != null) {
            sql.SET("is_controller_center = #{isControllerCenter,jdbcType=INTEGER}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUserId() != null) {
            sql.SET("create_user_id = #{createUserId,jdbcType=BIGINT}");
        }
        
        if (record.getHomeId() != null) {
            sql.SET("home_id = #{homeId,jdbcType=BIGINT}");
        }
        
        if (record.getIcName() != null) {
            sql.SET("ic_name = #{icName,jdbcType=VARCHAR}");
        }
        
        if (record.getFirmwareVersion() != null) {
            sql.SET("firmware_version = #{firmwareVersion,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}