package com.smart.homelink.dao;

import com.smart.homelink.model.SmartComponent;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SmartComponentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_component
     *
     * @mbg.generated
     */
    @Delete({
        "delete from smart_component",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_component
     *
     * @mbg.generated
     */
    @Insert({
        "insert into smart_component (id, type_id, ",
        "name, status, create_time, ",
        "is_controller_center, remark, ",
        "create_user_id, home_id, ",
        "ic_name, firmware_version)",
        "values (#{id,jdbcType=BIGINT}, #{typeId,jdbcType=BIGINT}, ",
        "#{name,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isControllerCenter,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR}, ",
        "#{createUserId,jdbcType=BIGINT}, #{homeId,jdbcType=BIGINT}, ",
        "#{icName,jdbcType=VARCHAR}, #{firmwareVersion,jdbcType=VARCHAR})"
    })
    int insert(SmartComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_component
     *
     * @mbg.generated
     */
    @InsertProvider(type=SmartComponentSqlProvider.class, method="insertSelective")
    int insertSelective(SmartComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_component
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, type_id, name, status, create_time, is_controller_center, remark, create_user_id, ",
        "home_id, ic_name, firmware_version",
        "from smart_component",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="type_id", property="typeId", jdbcType=JdbcType.BIGINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_controller_center", property="isControllerCenter", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_user_id", property="createUserId", jdbcType=JdbcType.BIGINT),
        @Result(column="home_id", property="homeId", jdbcType=JdbcType.BIGINT),
        @Result(column="ic_name", property="icName", jdbcType=JdbcType.VARCHAR),
        @Result(column="firmware_version", property="firmwareVersion", jdbcType=JdbcType.VARCHAR)
    })
    SmartComponent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_component
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SmartComponentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SmartComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smart_component
     *
     * @mbg.generated
     */
    @Update({
        "update smart_component",
        "set type_id = #{typeId,jdbcType=BIGINT},",
          "name = #{name,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_controller_center = #{isControllerCenter,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_user_id = #{createUserId,jdbcType=BIGINT},",
          "home_id = #{homeId,jdbcType=BIGINT},",
          "ic_name = #{icName,jdbcType=VARCHAR},",
          "firmware_version = #{firmwareVersion,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SmartComponent record);
}