package com.smart.homelink.dao;

import com.smart.homelink.model.TTest1;
import org.apache.ibatis.jdbc.SQL;

public class TTest1SqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1
     *
     * @mbg.generated
     */
    public String insertSelective(TTest1 record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_test1");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TTest1 record) {
        SQL sql = new SQL();
        sql.UPDATE("t_test1");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}