package com.smart.homelink.model;

import java.math.BigDecimal;
import java.util.Date;

public class AirSensorRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_sensor_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_sensor_record.c_id
     *
     * @mbg.generated
     */
    private Long cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_sensor_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_sensor_record.home_id
     *
     * @mbg.generated
     */
    private Long homeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_sensor_record.temp
     *
     * @mbg.generated
     */
    private BigDecimal temp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_sensor_record.humidity
     *
     * @mbg.generated
     */
    private BigDecimal humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_sensor_record.altitude
     *
     * @mbg.generated
     */
    private BigDecimal altitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_sensor_record.qnh
     *
     * @mbg.generated
     */
    private BigDecimal qnh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_sensor_record.id
     *
     * @return the value of air_sensor_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_sensor_record.id
     *
     * @param id the value for air_sensor_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_sensor_record.c_id
     *
     * @return the value of air_sensor_record.c_id
     *
     * @mbg.generated
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_sensor_record.c_id
     *
     * @param cId the value for air_sensor_record.c_id
     *
     * @mbg.generated
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_sensor_record.create_time
     *
     * @return the value of air_sensor_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_sensor_record.create_time
     *
     * @param createTime the value for air_sensor_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_sensor_record.home_id
     *
     * @return the value of air_sensor_record.home_id
     *
     * @mbg.generated
     */
    public Long getHomeId() {
        return homeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_sensor_record.home_id
     *
     * @param homeId the value for air_sensor_record.home_id
     *
     * @mbg.generated
     */
    public void setHomeId(Long homeId) {
        this.homeId = homeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_sensor_record.temp
     *
     * @return the value of air_sensor_record.temp
     *
     * @mbg.generated
     */
    public BigDecimal getTemp() {
        return temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_sensor_record.temp
     *
     * @param temp the value for air_sensor_record.temp
     *
     * @mbg.generated
     */
    public void setTemp(BigDecimal temp) {
        this.temp = temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_sensor_record.humidity
     *
     * @return the value of air_sensor_record.humidity
     *
     * @mbg.generated
     */
    public BigDecimal getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_sensor_record.humidity
     *
     * @param humidity the value for air_sensor_record.humidity
     *
     * @mbg.generated
     */
    public void setHumidity(BigDecimal humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_sensor_record.altitude
     *
     * @return the value of air_sensor_record.altitude
     *
     * @mbg.generated
     */
    public BigDecimal getAltitude() {
        return altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_sensor_record.altitude
     *
     * @param altitude the value for air_sensor_record.altitude
     *
     * @mbg.generated
     */
    public void setAltitude(BigDecimal altitude) {
        this.altitude = altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_sensor_record.qnh
     *
     * @return the value of air_sensor_record.qnh
     *
     * @mbg.generated
     */
    public BigDecimal getQnh() {
        return qnh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_sensor_record.qnh
     *
     * @param qnh the value for air_sensor_record.qnh
     *
     * @mbg.generated
     */
    public void setQnh(BigDecimal qnh) {
        this.qnh = qnh;
    }
}