package com.smart.homelink.model;

import java.util.Date;

public class ChatRoomMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.FROM_ACCOUNT
     *
     * @mbg.generated
     */
    private Long fromAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.FROM_CLIENT_TYPE
     *
     * @mbg.generated
     */
    private String fromClientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.MSGID_CLIENT
     *
     * @mbg.generated
     */
    private String msgidClient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.FROM_EXT
     *
     * @mbg.generated
     */
    private String fromExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.FROM_AVATOR
     *
     * @mbg.generated
     */
    private String fromAvator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.FROM_NICK
     *
     * @mbg.generated
     */
    private String fromNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.MSG_TIMESTAMP
     *
     * @mbg.generated
     */
    private Date msgTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.RESEND_FLAG
     *
     * @mbg.generated
     */
    private String resendFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.MSG_TYPE
     *
     * @mbg.generated
     */
    private String msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.CHAT_ROOM_ID
     *
     * @mbg.generated
     */
    private Long chatRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.QUIZ_OR_REPLY
     *
     * @mbg.generated
     */
    private String quizOrReply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.REPLY_ID
     *
     * @mbg.generated
     */
    private Long replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.REPLY_NAME
     *
     * @mbg.generated
     */
    private String replyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.REPLY_AVATOR
     *
     * @mbg.generated
     */
    private String replyAvator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.CUSTOM_MSG_TYPE
     *
     * @mbg.generated
     */
    private String customMsgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.IS_GARBAGE
     *
     * @mbg.generated
     */
    private String isGarbage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.COURSE_ID
     *
     * @mbg.generated
     */
    private Long courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.LIVE_TOPIC
     *
     * @mbg.generated
     */
    private String liveTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.START_PLAY_TIME
     *
     * @mbg.generated
     */
    private Long startPlayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.STOP_PLAY_TIME
     *
     * @mbg.generated
     */
    private Long stopPlayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.ATTACH
     *
     * @mbg.generated
     */
    private String attach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_room_msg.MSG_BODY
     *
     * @mbg.generated
     */
    private String msgBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.ID
     *
     * @return the value of chat_room_msg.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.ID
     *
     * @param id the value for chat_room_msg.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.FROM_ACCOUNT
     *
     * @return the value of chat_room_msg.FROM_ACCOUNT
     *
     * @mbg.generated
     */
    public Long getFromAccount() {
        return fromAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.FROM_ACCOUNT
     *
     * @param fromAccount the value for chat_room_msg.FROM_ACCOUNT
     *
     * @mbg.generated
     */
    public void setFromAccount(Long fromAccount) {
        this.fromAccount = fromAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.FROM_CLIENT_TYPE
     *
     * @return the value of chat_room_msg.FROM_CLIENT_TYPE
     *
     * @mbg.generated
     */
    public String getFromClientType() {
        return fromClientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.FROM_CLIENT_TYPE
     *
     * @param fromClientType the value for chat_room_msg.FROM_CLIENT_TYPE
     *
     * @mbg.generated
     */
    public void setFromClientType(String fromClientType) {
        this.fromClientType = fromClientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.MSGID_CLIENT
     *
     * @return the value of chat_room_msg.MSGID_CLIENT
     *
     * @mbg.generated
     */
    public String getMsgidClient() {
        return msgidClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.MSGID_CLIENT
     *
     * @param msgidClient the value for chat_room_msg.MSGID_CLIENT
     *
     * @mbg.generated
     */
    public void setMsgidClient(String msgidClient) {
        this.msgidClient = msgidClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.FROM_EXT
     *
     * @return the value of chat_room_msg.FROM_EXT
     *
     * @mbg.generated
     */
    public String getFromExt() {
        return fromExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.FROM_EXT
     *
     * @param fromExt the value for chat_room_msg.FROM_EXT
     *
     * @mbg.generated
     */
    public void setFromExt(String fromExt) {
        this.fromExt = fromExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.FROM_AVATOR
     *
     * @return the value of chat_room_msg.FROM_AVATOR
     *
     * @mbg.generated
     */
    public String getFromAvator() {
        return fromAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.FROM_AVATOR
     *
     * @param fromAvator the value for chat_room_msg.FROM_AVATOR
     *
     * @mbg.generated
     */
    public void setFromAvator(String fromAvator) {
        this.fromAvator = fromAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.FROM_NICK
     *
     * @return the value of chat_room_msg.FROM_NICK
     *
     * @mbg.generated
     */
    public String getFromNick() {
        return fromNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.FROM_NICK
     *
     * @param fromNick the value for chat_room_msg.FROM_NICK
     *
     * @mbg.generated
     */
    public void setFromNick(String fromNick) {
        this.fromNick = fromNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.MSG_TIMESTAMP
     *
     * @return the value of chat_room_msg.MSG_TIMESTAMP
     *
     * @mbg.generated
     */
    public Date getMsgTimestamp() {
        return msgTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.MSG_TIMESTAMP
     *
     * @param msgTimestamp the value for chat_room_msg.MSG_TIMESTAMP
     *
     * @mbg.generated
     */
    public void setMsgTimestamp(Date msgTimestamp) {
        this.msgTimestamp = msgTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.RESEND_FLAG
     *
     * @return the value of chat_room_msg.RESEND_FLAG
     *
     * @mbg.generated
     */
    public String getResendFlag() {
        return resendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.RESEND_FLAG
     *
     * @param resendFlag the value for chat_room_msg.RESEND_FLAG
     *
     * @mbg.generated
     */
    public void setResendFlag(String resendFlag) {
        this.resendFlag = resendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.MSG_TYPE
     *
     * @return the value of chat_room_msg.MSG_TYPE
     *
     * @mbg.generated
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.MSG_TYPE
     *
     * @param msgType the value for chat_room_msg.MSG_TYPE
     *
     * @mbg.generated
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.CHAT_ROOM_ID
     *
     * @return the value of chat_room_msg.CHAT_ROOM_ID
     *
     * @mbg.generated
     */
    public Long getChatRoomId() {
        return chatRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.CHAT_ROOM_ID
     *
     * @param chatRoomId the value for chat_room_msg.CHAT_ROOM_ID
     *
     * @mbg.generated
     */
    public void setChatRoomId(Long chatRoomId) {
        this.chatRoomId = chatRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.QUIZ_OR_REPLY
     *
     * @return the value of chat_room_msg.QUIZ_OR_REPLY
     *
     * @mbg.generated
     */
    public String getQuizOrReply() {
        return quizOrReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.QUIZ_OR_REPLY
     *
     * @param quizOrReply the value for chat_room_msg.QUIZ_OR_REPLY
     *
     * @mbg.generated
     */
    public void setQuizOrReply(String quizOrReply) {
        this.quizOrReply = quizOrReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.REPLY_ID
     *
     * @return the value of chat_room_msg.REPLY_ID
     *
     * @mbg.generated
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.REPLY_ID
     *
     * @param replyId the value for chat_room_msg.REPLY_ID
     *
     * @mbg.generated
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.REPLY_NAME
     *
     * @return the value of chat_room_msg.REPLY_NAME
     *
     * @mbg.generated
     */
    public String getReplyName() {
        return replyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.REPLY_NAME
     *
     * @param replyName the value for chat_room_msg.REPLY_NAME
     *
     * @mbg.generated
     */
    public void setReplyName(String replyName) {
        this.replyName = replyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.REPLY_AVATOR
     *
     * @return the value of chat_room_msg.REPLY_AVATOR
     *
     * @mbg.generated
     */
    public String getReplyAvator() {
        return replyAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.REPLY_AVATOR
     *
     * @param replyAvator the value for chat_room_msg.REPLY_AVATOR
     *
     * @mbg.generated
     */
    public void setReplyAvator(String replyAvator) {
        this.replyAvator = replyAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.CUSTOM_MSG_TYPE
     *
     * @return the value of chat_room_msg.CUSTOM_MSG_TYPE
     *
     * @mbg.generated
     */
    public String getCustomMsgType() {
        return customMsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.CUSTOM_MSG_TYPE
     *
     * @param customMsgType the value for chat_room_msg.CUSTOM_MSG_TYPE
     *
     * @mbg.generated
     */
    public void setCustomMsgType(String customMsgType) {
        this.customMsgType = customMsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.IS_GARBAGE
     *
     * @return the value of chat_room_msg.IS_GARBAGE
     *
     * @mbg.generated
     */
    public String getIsGarbage() {
        return isGarbage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.IS_GARBAGE
     *
     * @param isGarbage the value for chat_room_msg.IS_GARBAGE
     *
     * @mbg.generated
     */
    public void setIsGarbage(String isGarbage) {
        this.isGarbage = isGarbage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.COURSE_ID
     *
     * @return the value of chat_room_msg.COURSE_ID
     *
     * @mbg.generated
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.COURSE_ID
     *
     * @param courseId the value for chat_room_msg.COURSE_ID
     *
     * @mbg.generated
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.LIVE_TOPIC
     *
     * @return the value of chat_room_msg.LIVE_TOPIC
     *
     * @mbg.generated
     */
    public String getLiveTopic() {
        return liveTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.LIVE_TOPIC
     *
     * @param liveTopic the value for chat_room_msg.LIVE_TOPIC
     *
     * @mbg.generated
     */
    public void setLiveTopic(String liveTopic) {
        this.liveTopic = liveTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.START_PLAY_TIME
     *
     * @return the value of chat_room_msg.START_PLAY_TIME
     *
     * @mbg.generated
     */
    public Long getStartPlayTime() {
        return startPlayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.START_PLAY_TIME
     *
     * @param startPlayTime the value for chat_room_msg.START_PLAY_TIME
     *
     * @mbg.generated
     */
    public void setStartPlayTime(Long startPlayTime) {
        this.startPlayTime = startPlayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.STOP_PLAY_TIME
     *
     * @return the value of chat_room_msg.STOP_PLAY_TIME
     *
     * @mbg.generated
     */
    public Long getStopPlayTime() {
        return stopPlayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.STOP_PLAY_TIME
     *
     * @param stopPlayTime the value for chat_room_msg.STOP_PLAY_TIME
     *
     * @mbg.generated
     */
    public void setStopPlayTime(Long stopPlayTime) {
        this.stopPlayTime = stopPlayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.ATTACH
     *
     * @return the value of chat_room_msg.ATTACH
     *
     * @mbg.generated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.ATTACH
     *
     * @param attach the value for chat_room_msg.ATTACH
     *
     * @mbg.generated
     */
    public void setAttach(String attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_room_msg.MSG_BODY
     *
     * @return the value of chat_room_msg.MSG_BODY
     *
     * @mbg.generated
     */
    public String getMsgBody() {
        return msgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_room_msg.MSG_BODY
     *
     * @param msgBody the value for chat_room_msg.MSG_BODY
     *
     * @mbg.generated
     */
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody;
    }
}