package com.smart.homelink.model;

public class HomeUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_user.home_id
     *
     * @mbg.generated
     */
    private Long homeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_user.id
     *
     * @return the value of home_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_user.id
     *
     * @param id the value for home_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_user.home_id
     *
     * @return the value of home_user.home_id
     *
     * @mbg.generated
     */
    public Long getHomeId() {
        return homeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_user.home_id
     *
     * @param homeId the value for home_user.home_id
     *
     * @mbg.generated
     */
    public void setHomeId(Long homeId) {
        this.homeId = homeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_user.user_id
     *
     * @return the value of home_user.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_user.user_id
     *
     * @param userId the value for home_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}