package com.smart.homelink.model;

import java.util.Date;

public class Home {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home.home_name
     *
     * @mbg.generated
     */
    private String homeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home.belong_user_id
     *
     * @mbg.generated
     */
    private Long belongUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home.id
     *
     * @return the value of home.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home.id
     *
     * @param id the value for home.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home.home_name
     *
     * @return the value of home.home_name
     *
     * @mbg.generated
     */
    public String getHomeName() {
        return homeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home.home_name
     *
     * @param homeName the value for home.home_name
     *
     * @mbg.generated
     */
    public void setHomeName(String homeName) {
        this.homeName = homeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home.belong_user_id
     *
     * @return the value of home.belong_user_id
     *
     * @mbg.generated
     */
    public Long getBelongUserId() {
        return belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home.belong_user_id
     *
     * @param belongUserId the value for home.belong_user_id
     *
     * @mbg.generated
     */
    public void setBelongUserId(Long belongUserId) {
        this.belongUserId = belongUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home.status
     *
     * @return the value of home.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home.status
     *
     * @param status the value for home.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home.create_time
     *
     * @return the value of home.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home.create_time
     *
     * @param createTime the value for home.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}