package com.smart.homelink.model;

public class MResRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_res_rel.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_res_rel.res_id
     *
     * @mbg.generated
     */
    private Long resId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_res_rel.rel_id
     *
     * @mbg.generated
     */
    private Long relId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_res_rel.id
     *
     * @return the value of m_res_rel.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_res_rel.id
     *
     * @param id the value for m_res_rel.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_res_rel.res_id
     *
     * @return the value of m_res_rel.res_id
     *
     * @mbg.generated
     */
    public Long getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_res_rel.res_id
     *
     * @param resId the value for m_res_rel.res_id
     *
     * @mbg.generated
     */
    public void setResId(Long resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_res_rel.rel_id
     *
     * @return the value of m_res_rel.rel_id
     *
     * @mbg.generated
     */
    public Long getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_res_rel.rel_id
     *
     * @param relId the value for m_res_rel.rel_id
     *
     * @mbg.generated
     */
    public void setRelId(Long relId) {
        this.relId = relId;
    }
}