package com.smart.homelink.model;

import java.util.Date;

public class SmartComponentType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component_type.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component_type.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component_type.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component_type.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component_type.is_controller_center
     *
     * @mbg.generated
     */
    private Integer isControllerCenter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component_type.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component_type.id
     *
     * @return the value of smart_component_type.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component_type.id
     *
     * @param id the value for smart_component_type.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component_type.type_name
     *
     * @return the value of smart_component_type.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component_type.type_name
     *
     * @param typeName the value for smart_component_type.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component_type.status
     *
     * @return the value of smart_component_type.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component_type.status
     *
     * @param status the value for smart_component_type.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component_type.create_time
     *
     * @return the value of smart_component_type.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component_type.create_time
     *
     * @param createTime the value for smart_component_type.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component_type.is_controller_center
     *
     * @return the value of smart_component_type.is_controller_center
     *
     * @mbg.generated
     */
    public Integer getIsControllerCenter() {
        return isControllerCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component_type.is_controller_center
     *
     * @param isControllerCenter the value for smart_component_type.is_controller_center
     *
     * @mbg.generated
     */
    public void setIsControllerCenter(Integer isControllerCenter) {
        this.isControllerCenter = isControllerCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component_type.remark
     *
     * @return the value of smart_component_type.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component_type.remark
     *
     * @param remark the value for smart_component_type.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}