package com.smart.homelink.model;

import java.util.Date;

public class SmartComponent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.type_id
     *
     * @mbg.generated
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.is_controller_center
     *
     * @mbg.generated
     */
    private Integer isControllerCenter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.create_user_id
     *
     * @mbg.generated
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.home_id
     *
     * @mbg.generated
     */
    private Long homeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.ic_name
     *
     * @mbg.generated
     */
    private String icName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smart_component.firmware_version
     *
     * @mbg.generated
     */
    private String firmwareVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.id
     *
     * @return the value of smart_component.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.id
     *
     * @param id the value for smart_component.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.type_id
     *
     * @return the value of smart_component.type_id
     *
     * @mbg.generated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.type_id
     *
     * @param typeId the value for smart_component.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.name
     *
     * @return the value of smart_component.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.name
     *
     * @param name the value for smart_component.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.status
     *
     * @return the value of smart_component.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.status
     *
     * @param status the value for smart_component.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.create_time
     *
     * @return the value of smart_component.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.create_time
     *
     * @param createTime the value for smart_component.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.is_controller_center
     *
     * @return the value of smart_component.is_controller_center
     *
     * @mbg.generated
     */
    public Integer getIsControllerCenter() {
        return isControllerCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.is_controller_center
     *
     * @param isControllerCenter the value for smart_component.is_controller_center
     *
     * @mbg.generated
     */
    public void setIsControllerCenter(Integer isControllerCenter) {
        this.isControllerCenter = isControllerCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.remark
     *
     * @return the value of smart_component.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.remark
     *
     * @param remark the value for smart_component.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.create_user_id
     *
     * @return the value of smart_component.create_user_id
     *
     * @mbg.generated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.create_user_id
     *
     * @param createUserId the value for smart_component.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.home_id
     *
     * @return the value of smart_component.home_id
     *
     * @mbg.generated
     */
    public Long getHomeId() {
        return homeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.home_id
     *
     * @param homeId the value for smart_component.home_id
     *
     * @mbg.generated
     */
    public void setHomeId(Long homeId) {
        this.homeId = homeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.ic_name
     *
     * @return the value of smart_component.ic_name
     *
     * @mbg.generated
     */
    public String getIcName() {
        return icName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.ic_name
     *
     * @param icName the value for smart_component.ic_name
     *
     * @mbg.generated
     */
    public void setIcName(String icName) {
        this.icName = icName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smart_component.firmware_version
     *
     * @return the value of smart_component.firmware_version
     *
     * @mbg.generated
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smart_component.firmware_version
     *
     * @param firmwareVersion the value for smart_component.firmware_version
     *
     * @mbg.generated
     */
    public void setFirmwareVersion(String firmwareVersion) {
        this.firmwareVersion = firmwareVersion;
    }
}