package com.smart.homelink.model;

public class TTest2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test2.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test2.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test2.id
     *
     * @return the value of t_test2.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test2.id
     *
     * @param id the value for t_test2.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test2.name
     *
     * @return the value of t_test2.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test2.name
     *
     * @param name the value for t_test2.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }
}